Module 11 Case study 1

In [65]:
import pandas as pd
import numpy as np

In [66]:
ratings = pd.read_csv("Datasets/additional_resources_11_rpt_8xwiyud/BX_books_book_ratings_users/BX-Book-Ratings.csv")
books = pd.read_csv('Datasets/additional_resources_11_rpt_8xwiyud/BX_books_book_ratings_users/BX-Books.csv')
users = pd.read_csv('Datasets/additional_resources_11_rpt_8xwiyud/BX_books_book_ratings_users/BX-Users.csv')

C:\Users\Akshaya.N\AppData\Local\Temp\ipykernel_23888\1260345581.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Datasets/additional_resources_11_rpt_8xwiyud/BX_books_book_ratings_users/BX-Books.csv')
C:\Users\Akshaya.N\AppData\Local\Temp\ipykernel_23888\1260345581.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  users = pd.read_csv('Datasets/additional_resources_11_rpt_8xwiyud/BX_books_book_ratings_users/BX-Users.csv')

In [67]:
print(ratings.shape)
print(ratings.info())
ratings.head()

(1048575, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   user_id  1048575 non-null  int64
 1   isbn     1048575 non-null  object
 2   rating   1048575 non-null  int64
dtypes: int64(2), object(1)
memory usage: 24.0+ MB
None

   user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [68]:
print(books.shape)
print(books.info())
books.head()

(271379, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271379 entries, 0 to 271378
Data columns (total 5 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   isbn                 271379 non-null  object
 1   book_title           271379 non-null  object
 2   book_author          271377 non-null  object
 3   year_of_publication  271379 non-null  object
 4   publisher            271377 non-null  object
dtypes: object(5)
memory usage: 10.4+ MB
None

,isbn,book_title,book_author,year_of_publication,publisher
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company

In [69]:
print(users.shape)
print(users.info())
users.head()

(278859, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278859 entries, 0 to 278858
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   user_id   278859 non-null  object
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), object(2)
memory usage: 6.4+ MB
None

  user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [70]:
ratings.duplicated().sum()

np.int64(146)

In [71]:
ratings[ratings.duplicated]

         user_id      isbn  rating
11338        709  9.78E+12       9
21604       4334  6.31E+11       0
28622       6575  6.31E+11       0
58876      11676  9.78E+12       9
58877      11676  9.78E+12       9
...          ...       ...     ...
1047765   250634  9.78E+12       0
1047766   250634  9.78E+12      10
1047767   250634  9.78E+12      10
1047768   250634  9.78E+12      10
1047769   250634  9.78E+12       0

[146 rows x 3 columns]

In [72]:
ratings.drop_duplicates(inplace=True)

In [73]:
ratings.shape

(1048429, 3)

In [74]:
ratings.isna().sum()

user_id    0
isbn       0
rating     0
dtype: int64

In [75]:
# encode book codes

ratings['isbn_encoded'] = ratings['isbn'].astype('category').cat.codes

In [76]:
print(ratings['isbn'])
ratings['isbn_encoded']

0          034545104X
1           155061224
2           446520802
3          052165615X
4           521795028
              ...
1048570     451410777
1048571     452264464
1048572    048623715X
1048573     486256588
1048574     515069434
Name: isbn, Length: 1048429, dtype: object

0            4511
1           30815
2          158458
3            9704
4          177084
            ...
1048570    167557
1048571    169219
1048572      9215
1048573    171876
1048574    173457
Name: isbn_encoded, Length: 1048429, dtype: int32

In [77]:
from sklearn.neighbors import NearestNeighbors

X = ratings[['user_id','isbn_encoded','rating']]
knn = NearestNeighbors(metric='cosine', algorithm='brute')
knn.fit(X.values)

NearestNeighbors(algorithm='brute', metric='cosine')

In [78]:
# example for user 2

target_user = X[X['user_id'] == 2].values
distances, indices = knn.kneighbors(target_user, n_neighbors=3)

In [79]:
print(distances)
indices

[[0.00000000e+00 1.13464793e-13 1.33781874e-13]]

array([[9561, 9573, 9572]])

In [80]:
# neighbors and recommend books

neighbor_data = X.iloc[indices.flatten()]
recommended_books = neighbor_data['isbn_encoded'].unique()

In [81]:
# decode book codes

original_book_code = ratings[ratings['isbn_encoded'].isin(recommended_books)]['isbn'].unique()

In [82]:
original_book_code

array(['195153448', '771025661', '771074670'], dtype=object)

In [83]:
print('Recommended_books for the user are:')
for book in original_book_code:
    print(book)

Recommended_books for the user are:
195153448
771025661
771074670