Module 9 Case study 3

In [111]:
import pandas as pd

In [112]:
# SVM - binary classification
# preprocessing and hyperparameter search using grid search

In [113]:
#1 Load the data from “College.csv” that has attributes collected about private 
# and public colleges for a particular year. 
# We will try to predict the private/public status of the college from other attributes.


df = pd.read_csv('Datasets/additional_resources_9_ox6_o5534js/College.csv')
df

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
772,No,2197,1515,543,4,26,3089,2029,6797,3900,500,1200,60,60,21.0,14,4469,40
773,Yes,1959,1805,695,24,47,2849,1107,11520,4960,600,1250,73,75,13.3,31,9189,83
774,Yes,2097,1915,695,34,61,2793,166,6900,4200,617,781,67,75,14.4,20,8323,49
775,Yes,10705,2453,1317,95,99,5217,83,19840,6510,630,2115,96,96,5.8,49,40386,99
776,Yes,2989,1855,691,28,63,2988,1726,4990,3560,500,1250,75,75,18.1,28,4509,99

In [114]:
df['Private'].value_counts()

Private
Yes    565
No     212
Name: count, dtype: int64

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Private      777 non-null    object
 1   Apps         777 non-null    int64
 2   Accept       777 non-null    int64
 3   Enroll       777 non-null    int64
 4   Top10perc    777 non-null    int64
 5   Top25perc    777 non-null    int64
 6   F.Undergrad  777 non-null    int64
 7   P.Undergrad  777 non-null    int64
 8   Outstate     777 non-null    int64
 9   Room.Board   777 non-null    int64
 10  Books        777 non-null    int64
 11  Personal     777 non-null    int64
 12  PhD          777 non-null    int64
 13  Terminal     777 non-null    int64
 14  S.F.Ratio    777 non-null    float64
 15  perc.alumni  777 non-null    int64
 16  Expend       777 non-null    int64
 17  Grad.Rate    777 non-null    int64
dtypes: float64(1), int64(16), object(1)
memory usage: 109.4+ KB

In [116]:
#2 Use LabelEncoder to encode the target variable into numerical form and 
# split the data such that 20% of the data is set aside for testing.

from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()
df['Private'] = encode.fit_transform(df['Private'])
df[['Private']]

     Private
0          1
1          1
2          1
3          1
4          1
..       ...
772        0
773        1
774        1
775        1
776        1

[777 rows x 1 columns]

In [117]:
from sklearn.model_selection import train_test_split

X = df.drop('Private', axis=1)
y = df['Private']    # cannot pass a dataframe(or column vector) to y as the model expects 1d array

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [118]:
#3 Fit a linear SVM from scikit learn and observe the accuracy. 
# [Hint:Use Linear SVC]

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

svm = LinearSVC()
svm.fit(X_train, y_train)

ypred = svm.predict(X_test)

score = accuracy_score(y_test, ypred)
print('Accuracy score:', score)

Accuracy score: 0.9615384615384616

In [119]:
# finding the score using scikit score module

print(svm.score(X_test,y_test))

0.9615384615384616

In [120]:
#4 Preprocess the data using StandardScalar and fit the same model again and observe the change in accuracy.
# [Hint: Refer to scikitlearn’s preprocessing methods]

from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
svm_scaled = LinearSVC()

X_train_scaled = scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)

svm_scaled.fit(X_train_scaled, y_train)

print('Accuracy score:', svm_scaled.score(X_test_scaled, y_test))

Accuracy score: 0.9615384615384616

In [121]:
X_train_scaled

array([[-0.74919386, -0.74548646, -0.68335014, ...,  0.61624118,
        -0.55343127, -0.08403514],
       [-0.67374347, -0.61306765, -0.6144292 , ..., -0.37303699,
        -0.6949545 , -0.42925559],
       [-0.56714122, -0.50861849, -0.53128648, ...,  1.19332012,
         0.43009106,  0.83655272],
       ...,
       [ 0.59776705,  0.88156053,  0.44892241, ..., -1.11499563,
         0.16608525,  0.03103834],
       [ 3.10820723,  0.06213718,  0.89964346, ...,  2.42991784,
         5.03499681,  1.98728754],
       [-0.65430928, -0.6239933 , -0.55316614, ...,  0.69868103,
        -0.21674148,  1.29684665]], shape=(621, 17))

In [127]:
svm_scaled.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': 'auto',
 'fit_intercept': True,
 'intercept_scaling': 1,
 'loss': 'squared_hinge',
 'max_iter': 1000,
 'multi_class': 'ovr',
 'penalty': 'l2',
 'random_state': None,
 'tol': 0.0001,
 'verbose': 0}

In [ ]:
#5 Use scikit learns grid search to select the best hyperparameter for a non-linear SVM, and 
# identify the model with the best score and its parameters. 
# [Hint: Refer to model_selection module of Scikit learn]

from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

params = { 'C' : [0.1,1,10,100],
          'kernel' : ['rbf'],
          'gamma' : [0.001,0.01,0.1,1]
            }
gs = GridSearchCV(estimator=SVC(), param_grid = params, cv=5, scoring='accuracy', verbose=1)

gs.fit(X_train_scaled, y_train)

Fitting 10 folds for each of 16 candidates, totalling 160 fits

GridSearchCV(cv=10, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [0.001, 0.01, 0.1, 1],
                         'kernel': ['rbf']},
             scoring='accuracy', verbose=1)

In [139]:
print(gs.best_score_)
print(gs.best_params_)
print(gs.best_estimator_)
gs.score(X_test_scaled,y_test)

0.9371735791090631
{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
SVC(C=10, gamma=0.01)

0.9615384615384616

In [145]:
from sklearn.model_selection import cross_val_score

cv = cross_val_score(svm, X, y, cv=5).mean()
print(cv)

0.9356741108354012

In [146]:
print('Both the models show similar accuracies')

Both the models show similar accuracies